spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.hbm2ddl.auto: update
    database: MYSQL
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      min-idle: 5
      initial-size: 15
      max-active: 500
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      max-wait: 60000
      log-abandoned: true
      filters: stat
      filter:
        config:
          enabled: true
      stat-view-servlet:
        login-username: admin
        login-password: 123456















